from codrone_edu.drone import *
from math import sqrt

drone = Drone()
drone.pair()
drone.reset_sensor()
drone.takeoff()
print(f"Now at {drone.get_position_data()}, facing {drone.get_sensor_data()[14]}")
drone.set_pitch(30)
drone.move(3)
print(f"Now at {drone.get_position_data()}, facing {drone.get_sensor_data()[14]}")
drone.turn_degree(90)
print(f"Now at {drone.get_position_data()}, facing {drone.get_sensor_data()[14]}")
drone.set_pitch(30)
drone.move(3)
print(f"Now at {drone.get_position_data()}, facing {drone.get_sensor_data()[14]}")
drone.turn_degree(-45-90)
print(f"Now at {drone.get_position_data()}, facing {drone.get_sensor_data()[14]}")
drone.set_pitch(30)
drone.move(sqrt(2)*3)
print(f"Now at {drone.get_position_data()}, facing {drone.get_sensor_data()[14]}")
drone.land()